services:
  image-service:
    build: 
      context: .
      dockerfile: image.Dockerfile
    environment:
      - PORT=8081
    deploy:
      replicas: 2
    networks:
      - distributed-network
    volumes:
      - ./images:/images
        
  image-nginx-lb:
    image: nginx:1.27.3-alpine
    container_name: image-nginx-lb
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - distributed-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - image-service


  api-service:
    build: 
     context: .
     dockerfile: main.Dockerfile
    container_name: api-service
    ports:
      - "8080:8080"
    networks:
      - distributed-network
    volumes:
      - ./images:/images


networks:
  distributed-network:
    external: true